version: '3'

services:
  yoo-server:
    build: ./provisioning
    image: yoo
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached

  horizon:
    build: ./provisioning
    image: yoo
    command: php artisan horizon
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=yoo
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  #  mysql-test:
  #    image: mysql:5.7
  #    ports:
  #      - "3308:3306"
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=123456
  #      - MYSQL_DATABASE=testing

  nginx:
    image: nginx
    ports:
      - "8088:8000"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - yoo-server

  redis:
    image: redis
    ports:
      - "6379:6379"

  echo-server:
    image: node
    ports:
      - "8888:8888"
    working_dir: /application
    volumes:
      - .:/application:cached
    depends_on:
      - redis
      - yoo-server
    command: 'npm start'
